#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#    Jan 02, 2020 02:23:21 PM CST  platform: Windows NT

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk
finally:
    import api


def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    root.mainloop()


class Toplevel1:
    def __init__(self, top=None):
        '''This class configures and populates the toplevel window.
           top is the toplevel containing window.'''
        _bgcolor = '#d9d9d9'  # X11 color: 'gray85'
        _fgcolor = '#000000'  # X11 color: 'black'
        _compcolor = '#d9d9d9' # X11 color: 'gray85'
        _ana1color = '#d9d9d9' # X11 color: 'gray85'
        _ana2color = '#ececec' # Closest X11 color: 'gray92'

        top.geometry("672x599+711+215")
        top.minsize(180, 1)
        top.maxsize(1924, 1050)
        top.resizable(1, 1)
        top.title("New Toplevel")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.Label1 = tk.Label(top)
        self.Label1.place(relx=0.045, rely=0.05, height=50, width=108)
        self.Label1.configure(activebackground="#f9f9f9")
        self.Label1.configure(activeforeground="black")
        self.Label1.configure(background="#d9d9d9")
        self.Label1.configure(disabledforeground="#a3a3a3")
        self.Label1.configure(foreground="#000000")
        self.Label1.configure(highlightbackground="#d9d9d9")
        self.Label1.configure(highlightcolor="black")
        self.Label1.configure(text='''图片路径''')

        self.Entry1 = tk.Entry(top)
        self.Entry1.place(relx=0.208, rely=0.067,height=34, relwidth=0.72)
        self.Entry1.configure(background="white")
        self.Entry1.configure(disabledforeground="#a3a3a3")
        self.Entry1.configure(font="TkFixedFont")
        self.Entry1.configure(foreground="#000000")
        self.Entry1.configure(highlightbackground="#d9d9d9")
        self.Entry1.configure(highlightcolor="black")
        self.Entry1.configure(insertbackground="black")
        self.Entry1.configure(selectbackground="#c4c4c4")
        self.Entry1.configure(selectforeground="black")

        self.Button1 = tk.Button(top)
        self.Button1.place(relx=0.298, rely=0.167, height=40, width=83)
        self.Button1.configure(activebackground="#ececec")
        self.Button1.configure(activeforeground="#000000")
        self.Button1.configure(background="#d9d9d9")
        self.Button1.configure(disabledforeground="#a3a3a3")
        self.Button1.configure(foreground="#000000")
        self.Button1.configure(highlightbackground="#d9d9d9")
        self.Button1.configure(highlightcolor="black")
        self.Button1.configure(pady="0")
        self.Button1.configure(text='''确定''')
        self.Button1.configure(command=self.get_text)

        self.Scroll = tk.Scrollbar(top)
        self.Scroll.pack(side=tk.RIGHT, fill=tk.Y)

        self.Text1 = tk.Text(top)
        self.Text1.place(relx=0.074, rely=0.267, relheight=0.651, relwidth=0.854)
        self.Text1.configure(background="white")
        self.Text1.configure(font="TkTextFont")
        self.Text1.configure(foreground="black")
        self.Text1.configure(highlightbackground="#d9d9d9")
        self.Text1.configure(highlightcolor="black")
        self.Text1.configure(insertbackground="black")
        self.Text1.configure(selectbackground="#c4c4c4")
        self.Text1.configure(selectforeground="black")
        self.Text1.configure(wrap="word")
        self.Text1.config(yscrollcommand=self.Scroll.set)

        self.Scroll.config(command=self.Text1.yview)

        self.Button2 = tk.Button(top)
        self.Button2.place(relx=0.64, rely=0.167, height=40, width=83)
        self.Button2.configure(activebackground="#ececec")
        self.Button2.configure(activeforeground="#000000")
        self.Button2.configure(background="#d9d9d9")
        self.Button2.configure(disabledforeground="#a3a3a3")
        self.Button2.configure(foreground="#000000")
        self.Button2.configure(highlightbackground="#d9d9d9")
        self.Button2.configure(highlightcolor="black")
        self.Button2.configure(pady="0")
        self.Button2.configure(text='''清除''')
        self.Button2.configure(command=self.clear_text)

    def get_text(self):
        '''
        自定义函数
        点击确定按钮获得输入框的路径
        调用 api 模块，图片路径开始识别
        '''
        path = self.Entry1.get() # 获得路径
        text = api.main(path) # 识别
        self.Text1.insert('insert',text) # 在 gui 界面显示识别的文本

    def clear_text(self):
        '''
        自定义函数
        点击清除按钮，清空输入栏与文本框
        '''
        self.Entry1.delete(0,'end')
        self.Text1.delete('1.0', 'end')


if __name__ == '__main__':
    vp_start_gui()





